---
- name: "Check if variables are defined"
  include_tasks: check_variables.yml

- name: "Create LVs/FSes"
  include_tasks: lvm.yml
  when: sb_dedicated_lv_opt or sb_dedicated_lv_srv or sb_dedicated_lv_log

- name: "Deploy SELinux policy"
  include_tasks: selinux.yml

- name: "Create user and group"
  include_tasks: usersgroups.yml

- name: "Prepare Springboot root structures"
  include_tasks: directories.yml

- name: "Install SystemD service template"
  include_tasks: service.yml

