---

- name: "Create LV for /opt/springboot"
  lvol:
    vg: "{{ sb_dedicated_vg_opt }}"
    lv: lv_opt_springboot
    size: 1g
    state: present
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_opt

- name: "Initialise the XFS filesystem for /opt/springboot"
  filesystem:
    fstype: xfs
    dev: "/dev/{{ sb_dedicated_vg_opt }}/lv_opt_springboot"
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_opt

- name: "Mount /opt/springboot LV/FS"
  mount:
    path: /opt/springboot
    src: "/dev/{{ sb_dedicated_vg_opt }}/lv_opt_springboot"
    fstype: xfs
    state: mounted
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_opt

- name: "Create LV for /srv/springboot"
  lvol:
    vg: "{{ sb_dedicated_vg_srv }}"
    lv: lv_srv_springboot
    size: 1g
    state: present
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_srv

- name: "Initialise the XFS filesystem for /srv/springboot"
  filesystem:
    fstype: xfs
    dev: "/dev/{{ sb_dedicated_vg_srv }}/lv_srv_springboot"
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_srv

- name: "Mount /srv/springboot LV/FS"
  mount:
    path: /srv/springboot
    src: "/dev/{{ sb_dedicated_vg_srv }}/lv_srv_springboot"
    fstype: xfs
    state: mounted
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_srv

- name: "Create LV for /var/log/springboot"
  lvol:
    vg: "{{ sb_dedicated_vg_log }}"
    lv: lv_log_springboot
    size: 1g
    state: present
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_log

- name: "Initialise the XFS filesystem for /var/log/springboot"
  filesystem:
    fstype: xfs
    dev: "/dev/{{ sb_dedicated_vg_log }}/lv_log_springboot"
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_log

- name: "Mount /var/log/springboot LV/FS"
  mount:
    path: /var/log/springboot
    src: "/dev/{{ sb_dedicated_vg_log }}/lv_log_springboot"
    fstype: xfs
    state: mounted
  become: "{{ sb_become }}"
  when: sb_dedicated_lv_log
