---

- name: Ensure the springboot-systemd RPM is present
  package:
    name: springboot-systemd
    state: present
  become: "{{ sb_become }}"

- name: Enable the Install systemd Springboot target unit
  systemd:
    name: "springboot.target"
    enabled: sb_systemd_target_enabled
    daemon_reload: yes
