---
- name: Ensure group "springboot" exists with correct GID
  ansible.builtin.group:
    name: springboot
    state: present
    gid: {{ sb_group_id }}
  become: "{{ sb_become }}"

- name: Ensure user "springboot" exists with correct UID/GID
  ansible.builtin.user:
    name: springboot
    uid: {{ sb_user_id }}
    group: springboot
    shell: /sbin/nologin
    password: '!'
