---
- name: "Deploy Springboot instance"
  include_tasks: core.yml
  when:
    - not sb_undeploy
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 7

- name: "Undeploy Springboot instance"
  include_tasks: undeploy.yml
  when:
    - sb_undeploy
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 7
    - sb_become
