---

# Tasks to attempt to stop the Server
# Tries to first stop the server via an existing service.
# If that fails, it will check if the application folder
# exists and try to stop the server from command line.

# Attempt to stop the existing service

- block:
    - name: "Check service-file (systemd unit-file) status" # do not confuse this with the service status !
      systemd:
        name: "{{ sb_service_name }}"
      become: "{{ sb_become }}"
      register: sb_systemd_result

    # Stop1: First trial to stop the springboot for our instance using service
    - name: "Stop Springoot instance (RHEL 7/8)"
      systemd:
        name: "{{ sb_service_name }}"
        state: stopped
      become: "{{ sb_become }}"
      register: sb_service_stop
      when:
        - sb_systemd_result is defined and sb_systemd_result.status is defined and sb_systemd_result.status.UnitFileState is defined and sb_systemd_result.status.UnitFileState == 'enabled'

    - name: "Output of RHEL 7/8 stop attempt"
      debug:
        var: sb_service_stop
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 7
    - sb_become

# Stop2 (last chance): Try to stop any Java process with the AppName
- name: "Stop the Springboot Server (via process identification), using pkill command for any java process started with our app_name as argument"
  shell: pkill -f '^([^/]*/)*java\s+(.*?\s+)?-DAPP_NAME={{ sb_appname | regex_escape() }}(\s+.*)?$'
  become: "{{ sb_become }}"
  register: sb_pkill_output_cmd
  failed_when: sb_pkill_output_cmd.stderr_lines|length > 0
  changed_when: sb_pkill_output_cmd.rc == 0
