---

- name: "Attempt to stop server"
  include_tasks: stop_server.yml

- name: "Remove Springboot service"
  include_tasks: remove_service.yml

- name: Remove files (only on RHEL7 and higher)
  block:
    - name: Find extra files
      find:
        paths: "{{ sb_extra_files_src }}"
      when: sb_extra_files_src is defined and sb_remove_extra_files
      register: found_extra_files
      delegate_to: localhost

    - name: Find keystores
      find:
        paths: "{{ sb_keystores_src }}"
      when: sb_keystores_src is defined and sb_remove_keystores
      register: found_keystores
      delegate_to: localhost

    - name: Remove extra files
      file:
        state: absent
        path: "{{ sb_extra_files_dest }}/{{ item }}"

      loop: "{{ found_extra_files.files | map(attribute='path') | regex_replace(sb_extra_files_src|regex_escape() +'/', '') }}"
      when: sb_extra_files_src is defined and sb_remove_extra_files
      become: "{{sb_become}}"

    - name: Remove main application folder /opt
      file:
        state: absent
        path: "{{ sb_appbase }}"
      become: "{{sb_become}}"

    - name: Remove main application folder /srv
      file:
        state: absent
        path: "{{ sb_srv_dir }}"
      become: "{{sb_become}}"
